"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sendNewsletter = void 0;
const utils_1 = require("../utils");
const googleapis_1 = require("googleapis");
async function sendNewsletter() {
    // Query jobs processed
    const snapshot = await utils_1.listingsCollection.where('status', '==', 'processed').get();
    if (snapshot.empty) {
        console.log("No processed jobs to send.");
        return { sent: false, reason: "No jobs" };
    }
    const jobs = snapshot.docs.map(doc => doc.data());
    // Sort by score descending (League of Listings)
    jobs.sort((a, b) => (b.score || 0) - (a.score || 0));
    // Generate HTML
    let html = `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #2c3e50;">Your AI Job Scout Digest 🚀</h1>
            <p>Here are your top matches for the week, ranked by the Matching Agent.</p>
            <hr />
    `;
    for (const job of jobs) {
        html += `
            <div style="margin-bottom: 20px; padding: 15px; border: 1px solid #e0e0e0; border-radius: 8px;">
                <h2 style="margin: 0; color: #1a73e8;">${job.title} @ ${job.company}</h2>
                <p><strong>Match Score: ${job.score}%</strong></p>
                <p><em>${job.description_snippet}</em></p>
                
                <h4 style="margin-bottom: 5px; color: #0d652d;">Pros:</h4>
                <ul style="margin-top: 0; padding-left: 20px;">
                    ${(job.pros || []).map((p) => `<li>${p}</li>`).join('')}
                </ul>
                
                <h4 style="margin-bottom: 5px; color: #b31412;">Cons / Dealbreakers:</h4>
                <ul style="margin-top: 0; padding-left: 20px;">
                    ${(job.cons || []).map((c) => `<li>${c}</li>`).join('')}
                </ul>
                
                <p><strong>Gap Analysis:</strong> ${job.gap_analysis}</p>
                
                <a href="${job.url}" style="display: inline-block; padding: 10px 15px; background: #1a73e8; color: white; text-decoration: none; border-radius: 5px; margin-top: 10px;">Apply Now</a>
            </div>
        `;
    }
    html += `
        <p style="text-align: center; color: #888; font-size: 12px;">Generated by your AI Job Scout Multi-Agent System</p>
        </div>
    `;
    // Try to send via Gmail API
    const CLIENT_ID = process.env.GMAIL_CLIENT_ID;
    const CLIENT_SECRET = process.env.GMAIL_CLIENT_SECRET;
    const REFRESH_TOKEN = process.env.GMAIL_REFRESH_TOKEN;
    if (!CLIENT_ID || !CLIENT_SECRET || !REFRESH_TOKEN) {
        console.warn("Gmail OAuth variables missing. Dumping HTML to console instead:");
        console.log("================ NEWSLETTER HTML ================");
        console.log(html);
        console.log("=================================================");
        return { sent: false, reason: "Missing credentials", html };
    }
    try {
        const oAuth2Client = new googleapis_1.google.auth.OAuth2(CLIENT_ID, CLIENT_SECRET, 'https://developers.google.com/oauthplayground');
        oAuth2Client.setCredentials({ refresh_token: REFRESH_TOKEN });
        const gmail = googleapis_1.google.gmail({ version: 'v1', auth: oAuth2Client });
        const utf8Subject = `=?utf-8?B?${Buffer.from("Your Weekly AI Job Scout Digest 🚀").toString('base64')}?=`;
        const messageParts = [
            'From: AI Job Scout <me>',
            'To: <me>',
            'Content-Type: text/html; charset=utf-8',
            'MIME-Version: 1.0',
            `Subject: ${utf8Subject}`,
            '',
            html
        ];
        const message = messageParts.join('\n');
        const encodedMessage = Buffer.from(message).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
        await gmail.users.messages.send({
            userId: 'me',
            requestBody: {
                raw: encodedMessage,
            },
        });
        console.log("Newsletter sent successfully!");
        // Update status so they aren't sent again
        const batch = utils_1.db.batch();
        snapshot.docs.forEach((doc) => {
            batch.update(doc.ref, { status: 'notified' });
        });
        await batch.commit();
        return { sent: true };
    }
    catch (error) {
        console.error("Failed to send email:", error);
        return { sent: false, error: String(error) };
    }
}
exports.sendNewsletter = sendNewsletter;
//# sourceMappingURL=notification.js.map